### ISSUE TITLE
Refine visual design of service page

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/janis#60] opened 2018-01-03 18:29 UTC
- [ ] Refine service page template steps - step numbers have ovals around them now

- [ ] Remove 'United States' from contact address

- [ ] Update breadcrumb styling on service page: desktop includes full path, mobile and tablet shows only topic level

- [ ] Tag all addresses, phone numbers, and email addresses so they're in link format

- [ ] Lengthen desktop max character limit/line length to 720

**Comment by mateoclarke** [comment] 2018-01-17 21:51
@cthibaultatx, you mentioned IRL that you wanted this prioritized and completed before next Tuesday. We'll need more clarity on what you're asking in each of these tasks. Going to move this to "Blocked" until we have mocks and/or more details.

**Comment by succarwagner** [comment] 2018-01-23 20:22
@cthibaultatx could you please catch me up on color, visual distinctions and other styling direction? Thanks.

**Comment by cthibaultatx** [comment] 2018-02-01 15:11
@mateoclarke @ifsimicoded added boatload of service page updates. If any of them are unclear, please send me a note so I can refine.

**Comment by ifsimicoded** [comment] 2018-03-26 19:59
Closing as duplicate of closed issue https://github.com/cityofaustin/techstack/issues/140

**Closed by ifsimicoded** 2018-03-26 19:59 UTC
Labels: MVP, effort: medium
