### ISSUE TITLE
Translate content other than service content into 3 languages

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/janis#152] opened 2018-02-16 15:17 UTC
Translate content for:
- [ ] global navigation

- [ ] footer

- [ ] 311 module

- [ ] feedback form (need to finalize with content team)

- [ ] work in progress message/bar

- [ ] theme items

- [ ] topics that will be on next release

- [ ] service module content

- [ ] theme page content

- [ ] topic page content

- [ ] department and service page contact module copy that's not a phone #, address, or email

- [ ] breadcrumbs and menu should be covered...but need to check that one, too

- [ ] other service page headers

- [ ] notification IF a page/content has not, for whatever reason- been translated yet

**Comment by ifsimicoded** [comment] 2018-03-08 21:58
duplicate of https://github.com/cityofaustin/techstack/issues/112

**Closed by ifsimicoded** 2018-03-08 21:58 UTC
