### ISSUE TITLE
Translation for static/application content

### ISSUE THREAD

**Issue by ashleecoa** [cityofaustin/janis#111] opened 2018-01-22 18:12 UTC
## Bug Report
We need to determine how to translate content that is static and English into other languages. Also, for embedded applications, how do we get those to auto-translate based on the language the user has selected. 

#### What is the URL
http://austintexas.gov/page/my-collection-schedule

#### What type of device are you using — desktop or laptop, tablet, or phone? 
Laptop
#### What browser [browser info](https://www.whatismybrowser.com/) are you using? 
Firefox

![collection](https://user-images.githubusercontent.com/20669798/35236597-7c3c2418-ff6d-11e7-9532-7936140e29d8.jpg)

**Comment by ifsimicoded** [comment] 2018-03-08 21:57
duplicate of https://github.com/cityofaustin/techstack/issues/112

**Closed by ifsimicoded** 2018-03-08 21:57 UTC
Labels: effort: high
